### ISSUE TITLE
Medium: change the overall progress value during DB generation in GUI when it starts

### ISSUE THREAD

**Issue by EugeniaVoytik** [MannLabs/alphapept#186]
**Is your feature request related to a problem? Please describe.**
The overall progress during DB generation starts only in several minutes after the running of the tool.

**Describe the solution you'd like**
Maybe, it would be better to show from the beginning 0.1% when the user just run the tool. Otherwise, it could look like that nothing happens. (see the screenshot - https://i.gyazo.com/cb1c9bb4d2721d4074147183881ce3a8.jpg)

**Comment by straussmaximilian** [comment]
Should now be addressed with the new Streamlit GUI.
