### ISSUE TITLE
[Medium] "Auto-Update Page" checkbox is automatically unchecked when user switches between different sections

### ISSUE THREAD

**Issue by EugeniaVoytik** [MannLabs/alphapept#203]
**To Reproduce**
1. Run AlphaPept and in the "Status" section check "Auto-Update Page" check box.  
2. Switch to any other section, i.e. "New experiment".
3. Switch back to the "Status" section and check that the "Auto-Update Page" check box is again unchecked. 

**Expected behavior**
It would be nice to save the checking/unchecking of this check box during switching between the sections.

**Version (please complete the following information):**
 - OS: Windows
 - Version: 10.0.19041
 - Installation Type: One-Click Installer

**Comment by straussmaximilian** [comment]
Revised to now auto-update.
