### ISSUE TITLE
Selection of multiple proteases

### ISSUE THREAD

**Issue by ibludau** [MannLabs/alphapept#222]
**Is your feature request related to a problem? Please describe.**
Some people use multiple proteases in one experiment. It would be cool if it were possible to also select multiple proteases in alphapept.

<img width="1344" alt="Screenshot 2021-05-19 at 15 43 18" src="https://user-images.githubusercontent.com/20396322/118823020-f17e1f80-b8b8-11eb-827b-120c9c7260c8.png">

**Comment by straussmaximilian** [comment]
Moved to discussions (https://github.com/MannLabs/alphapept/discussions/324)
