### ISSUE TITLE
Compatibility of workflow steps

### ISSUE THREAD

**Issue by ibludau** [MannLabs/alphapept#226]
**Describe the bug**
Currently people can select 'lfq_quantification' without ever having imported or searched any file. It would be important to make the selection of workflow steps somehow linked to whether an hdf file with required information is already there.

Importantly, in these cases, the settings files need to somehow be saved differently to ensure that users can still follow how the final results were created in case multiple different settings were used and then stacked on top of each other.

**Comment by straussmaximilian** [comment]
Moved to suggestions.
