### ISSUE TITLE
[High] Impossible to reanalyze the file if the previous analysis was terminated

### ISSUE THREAD

**Issue by EugeniaVoytik** [MannLabs/alphapept#230]
**Describe the bug**
If terminate the analysis process at any point (f.e. FF) and after that try to rerun the analysis using default workflow steps, 
"Processing of D:\04_hela_testrun\20190402_QX1_SeVW_MA_HeLa_500ng_LC11.ms_data.hdf for step raw_conversion failed. Exception File extension .hdf not understood." exception occurs in the terminal and the program is frozen.

**To Reproduce**
1. Run any analysis with any settings and terminate the process, f.e. at the FF stage.
2. In the New experiment section enter the path to the same folder again. Here we see that .ms_data.hdf file appears as in the Raw files section (I also don't think that it should be included in this section- 
![image](https://user-images.githubusercontent.com/33324675/119819586-d16de200-bef0-11eb-961a-e5f668c23efb.png)
)
3. Leave all other options as default ones (continue_runs check box in the Workflow shouldn't be selected which means that ms_data file should be deleted) and Submit an experiment.
4. "Processing of D:\04_hela_testrun\20190402_QX1_SeVW_MA_HeLa_500ng_LC11.ms_data.hdf for step raw_conversion failed. Exception File extension .hdf not understood." occurs in the log and the whole run is frozen (longer than 30 minutes). (see attached log.file)

**Expected behavior**
It should be possible to rerun any terminated processes again. 
As a suggestion, maybe, it makes sense not to show the .ms_data.hdf in the Raw files section.

**Version (please complete the following information):**
 - OS: Windows
 - Version: 10.0.19042
 - Installation Type: One-Click Installer v.0.3.23

**Attached log file.**
[2021_05_27_thermo_hela_run2.log](https://github.com/MannLabs/alphapept/files/6553783/2021_05_27_thermo_hela_run2.log)

**Comment by straussmaximilian** [comment]
Should be fixed by now.
