### ISSUE TITLE
Settings reset when the setting group is unchecked

### ISSUE THREAD

**Issue by JuliaS92** [MannLabs/alphapept#239]
**Describe the bug**
If one unticks a setting group for a new experiment after adjusting the settings within they are reset to defaults without making it obvious to the user.

**To Reproduce**
1. Set up a new experiment
2. Tick general settings and adjust the process number
3. Untick the gernel settings
4. Save the yaml (reset to default), or tick the general settings again (also reset to default)

**Expected behavior**
I would expect the tick box to provide the same functionality as a details element, i.e. showing/hiding the setting without changing it. If this is the purpose one could replace it with a details or tabs for each setting group. I would personally prefer tabs to limit the scrolling length of the page. If the purpose is to change settings, make it into a button 'change general settings' and add a confirm/discard button group to make it unmistakably clear what happens to the settings.

**Version (please complete the following information):**
 - OS: Windows
 - Version 0.3.25
 - One-Click Installer

**Comment by straussmaximilian** [comment]
Now added some more documentation to make behaviour of UI more clear.
