### ISSUE TITLE
Add checkboxes to raw file list

### ISSUE THREAD

**Issue by JuliaS92** [MannLabs/alphapept#242]
**Is your feature request related to a problem? Please describe.**
I often want to run different analysis runs on different selections of files, or simply exclude reinjections from the analysis. Currently all raw files in a folder are analysed, which would mean moving raw files around a lot to adjust the analysis.

**Describe the solution you'd like**
You could add a checkbox for every raw file to unselect the ones you want to exclude for the current run.

**Additional context**
This includes hdf files from previous analyses, which should however be fixed by #241 as long as you don't look for files recursively (didn't check whether that is the case)

**Comment by straussmaximilian** [comment]
Files can now be excluded with the new file input widget.
![Screenshot 2021-09-09 at 16 14 16](https://user-images.githubusercontent.com/16521288/132702311-84a29c11-d6e9-4f3b-8095-21e99224548a.png)
