### ISSUE TITLE
Reflect function in design

### ISSUE THREAD

**Issue by JuliaS92** [MannLabs/alphapept#243]
**Is your feature request related to a problem? Please describe.**
I have to admit that I am quite overwhelmed/annoyed by the largely unstructured, list-like arrangement of the settings for a new experiment. Without even changing anything but the folder I already have to scroll to get an overview of my options, which only gets worse with every setting I adjust. Personally I would prefer it if the default settings were easily visible even if I don't want to change the settings, to even know what I can change.

**Describe the solution you'd like**
To make the settings less overwhelming and to 'reflect function in design' I would:
- avoid whitespace unless it's meaningful, in particular at the top of the page so you don't have to scroll straight away
- use tabs or steps, so all information for the currently focused block (either tab or step) can be displayed on a shorter page lenght
- make use of the 2nd dimension, e.g. put minimal and maximal peptide lenght next to each other (or even on a single two-value slider), same for variable and fixed modification types.
- put functionally linked settings closer together, e.g. missed cleavages and protease
- fix the submission at the bottom of the page to avoid excessive scrolling towards the end
- use more visible visual cues to group the settings (e.g. add brackets along the length of a block, make hrules thicker)

**Describe alternatives you've considered**
I've literally zoomed out the webpage to get a better overview.

**Additional context**
This is part of the reason why I unticked the settings and then wrote #239, when I realized what it does.

I know that this touches the very core of the interface and goes against clean/modern design thinking, but I personally think the functionality and user friendlyness are more important. This would be particularly important to pick up users of other tools (both Spectronaut and MaxQuant) where they come from.

**Comment by straussmaximilian** [comment]
Moved to suggestions.
