### ISSUE TITLE
Update alphapept from within

### ISSUE THREAD

**Issue by JuliaS92** [MannLabs/alphapept#245]
**Is your feature request related to a problem? Please describe.**
For anybody less familiar with python, or less comfortable with computers in general a software update will be a pain as it is now.

**Describe the solution you'd like**
Add an update button to the version number. Can be restricted to the one-click installer version.

**Additional context**
Minimally it would be good to highlight whether a new version is available and provide a step by step guide to an update.

**Comment by straussmaximilian** [comment]
Moved to discussions https://github.com/MannLabs/alphapept/discussions/330
