### ISSUE TITLE
PRIDE compatible data download

### ISSUE THREAD

**Issue by JuliaS92** [MannLabs/alphapept#246]
**Is your feature request related to a problem? Please describe.**
We need to be able to upload our data with PRIDE as easily as possible.

**Describe the solution you'd like**
Ideally a complete submission to PRIDE should be as simple as possible. Here are some ressources to check the requirements:
https://www.ebi.ac.uk/pride/markdownpage/submitdatapage#complete_and_partial_submissions
https://www.ebi.ac.uk/pride/markdownpage/specificsoftwareformats

**Comment by straussmaximilian** [comment]
Moved to Discussions https://github.com/MannLabs/alphapept/discussions/329
