### ISSUE TITLE
Auto-generate experiment name based on RAW file

### ISSUE THREAD

**Issue by treitpeter** [MannLabs/alphapept#261]
Would be easier if Alphapept would just autogenerate the experiment name based on the RAW file, that could then be edited if needed. 

In metaproteomics, we typically run the analysis against several different FASTA file options. So in my case, actually the best case scenario would be if the experiment name is a combination of RAW file and FASTA file

**Comment by straussmaximilian** [comment]
Multiple files should be processed together, e.g. to apply LFQ.
For the FASTA files one could implement a FASTA screening mode. 
To be performant one would have to ideally only change the search and keep file conversion / feature finding.
However, one could also just combine all FASTA files and then later try to disentangle the results.

**Comment by straussmaximilian** [comment]
Closed to inactivity.
