### ISSUE TITLE
Semi-specific digest, search and reporting

### ISSUE THREAD

**Issue by DoerigC** [MannLabs/alphapept#266]
**Is your feature request related to a problem? Please describe.**
Due to its high specificity, trypsin is the enzyme of choice in shotgun proteomics. Nonetheless, several publications do report the identification of semi-tryptic peptides: peptides which were cleaved at the C-Terminal side of R and K by trypsin at one end but not the other.
These peptides are also important for a handful of specialized workflows such as LiP-MS (https://doi.org/10.1038/nprot.2017.100)

**Describe the solution you'd like**
It would be nice to have the option to set the specificity of the digest to semi-specific. As a consequence, the cleave_sequence function could generate sequences that match a trypsin digest on either the C- or N-term of the peptide – but not necessarily both.

Ideally, these sequences would then not only be searched for, but their specificity (fully, specific-N-term or specific-C-term) could also be reported in the output tables. As an example report I added a screenshot of such a report from Spectronaut.

**Describe alternatives you've considered**
Alternatively, one could use the already implemented unspecific search and then filter the identified peptides in the downstream analysis by matching them to the fasta and determine the specificity.

**Additional context**
Attached screenshot of a sample report (see above)
![image](https://user-images.githubusercontent.com/57660388/125258388-95ef7180-e2fe-11eb-9566-691be5816668.png)

**Comment by straussmaximilian** [comment]
Closed for inactivity. Feel free to comment in case.
