### ISSUE TITLE
RAW files required, even when already processed in HDF

### ISSUE THREAD

**Issue by swillems** [MannLabs/alphapept#280]
**Is your feature request related to a problem? Please describe.**
Cannot start an anlysis from an HDF file without raw data, even if the raw data has already been converted and feature finding was already performed.

**Describe the solution you'd like**
An HDF file with raw data should suffice for (re)analysis, without needing to copy the raw data.

**Comment by straussmaximilian** [comment]
Quick fix is the solution for this for now.
