### ISSUE TITLE
Can anyone tell me how to resolve this error

### ISSUE THREAD

**Issue by amakaju** [MannLabs/alphapept#296]
(alphapept) C:\alphapeppt\alphapept>python -m alphapept gui

An exception occured running AlphaPept version 0.3.27:

....................................................

cupy_backends.cuda.api.runtime does not export expected C variable errorContextIsDestroyed

....................................................
Please visit https://github.com/MannLabs/alphapept and report this issue. Thanks.

**Comment by straussmaximilian** [comment]
Hi, 
do you have AlphaPept installed in a separate environment? (e.g. with conda)? What operating system are you using?
At first glance, it looks like a problem with cupy.
To get started I would recommend trying the CPU version first and follow the respective installation instructions on the readme.
I hope this helps.

**Comment by amakaju** [comment]
thank you very much there was a miss-match between CUDA version and the CUPY version. It is working now.
Thanks once again

**Comment by straussmaximilian** [comment]
Awesome, glad that it worked out!
