### ISSUE TITLE
crash on startup (windows quickstart)

### ISSUE THREAD

**Issue by Begbo95** [MannLabs/alphapept#297]
hi y'all!
version 0.3.26 .exe crashes immediately after start. 
when executing via command line this is the output:

Microsoft Windows [Version 10.0.19041.1110]
(c) Microsoft Corporation. All rights reserved.

C:\Users\admin>"C:\Program Files (x86)\AlphaPept\alphapept.exe"

     ___    __      __          ____             __
    /   |  / /___  / /_  ____  / __ \___  ____  / /_
   / /| | / / __ \/ __ \/ __ \/ /_/ / _ \/ __ \/ __/
  / ___ |/ / /_/ / / / / /_/ / ____/ ___/ /_/ / /_
 /_/  |_/_/ .___/_/ /_/\__,_/_/    \___/ .___/\__/
         /_/                          /_/
....................................................
.      https://github.com/MannLabs/alphapept       .
.                    Mann Labs                     .
.                      0.3.26                      .
....................................................

Usage: alphapept.exe [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help  Show this message and exit.

Commands:
  database     Create a database from a fasta file.
  export       Export protein table from `.ms_data.hdf` files as `.csv`.
  features     Find features in a `.ms_data.hdf` file.
  gui          Start graphical user interface for AlphaPept.
  import       Import and convert raw data from vendor to `.ms_data.hdf` file.
  quantify     Quantify and compare multiple `.ms_data.hdf` files.
  recalibrate  Recalibrate a `.ms_data.hdf` file.
  score        Score PSM from a `.ms_data.hdf` file.
  search       Search and identify feature in a `.ms_data.hdf` file.
  workflow     Run the complete AlphaPept workflow.

C:\Users\admin>

Am I doing something wrong?
best,
ben :)

**Comment by straussmaximilian** [comment]
Hi,
Do you receive an additional error message, or is this the output that you receive?

From what I see, this is actually the desired output from the `cmd`:
If no command is passed, it shows you all existing commands and then quits.

You need to pass an additional command so that It does something (e.g. `alphapept.exe gui`)

I hope that helps, and let me know if this solves the problem.

**Comment by Begbo95** [comment]
adding 'gui' to commandline worked! thanks for the quick answer :) 
but running the .exe straight from windows start-menu still causes it to shut down immediately. is there a way to add the 'gui' to the .exe so that i don't need to go through the command prompt every time?

**Comment by straussmaximilian** [comment]
Ah, very good point.
There should actually be a desktop shortcut to directly start the GUI.
I'll keep this PR open so that we can add functionality to better launch from start-menu.

**Comment by straussmaximilian** [comment]
The above commit should now fix this issue, which will be released with `v0.3.28` Launching from Windows Taskbar will now automatically launch the GUI.
