### ISSUE TITLE
Issue duringn docker build

### ISSUE THREAD

**Issue by amakaju** [MannLabs/alphapept#300]
Hi ,
I am getting following error during docker build. Any solutions/ideas.
executor failed running [/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF   && echo "deb http://download.mono-project.com/repo/debian stretch/snapshots/5.20 main" > /etc/apt/sources.list.d/mono-official.list   && apt-get update   && apt-get install -y clang   && apt-get install -y mono-devel=5.20\*   && rm -rf /var/lib/apt/lists/* /tmp/*]: exit code: 100

**Comment by straussmaximilian** [comment]
Hi,

my first guess would be that this is an http issue. Can you execute these commands on your host system?
I quickly checked the dockerization and there seem to be a couple of bugs, so I removed the installation instructions for docker for now. There is now a new issue where the status will be tracked: #302
