### ISSUE TITLE
An exception occured running AlphaPept version 0.3.26:

### ISSUE THREAD

**Issue by chaerkadyr** [MannLabs/alphapept#306]
I got the following error when I started AlphaPept. 
An exception occurred running AlphaPept version 0.3.26:
...................................................
The current Numpy installation ('C:\\Program Files (x86)\\AlphaPept\\numpy\\__init__.pyc') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
...................................................

Thanks for your help
Raghothama Chaerkady
email: raghothama.chaerkady@astrazeneca.com

**Comment by straussmaximilian** [comment]
Hi,
Thanks for reporting.
The issue is related to an outdated Windows version that doesn't have the patch KB4598291.
In this case, AlphaPept will not start. Updating Windows should solve the problem (see: https://tinyurl.com/y3dm3h86)

I hope this helps!

**Comment by chaerkadyr** [comment]
Thanks for the quick reply. After updating with the patch, I see different message.. 
...................................................
.      https://github.com/MannLabs/alphapept       .
.                    Mann Labs                     .
.                      0.3.26                      .
....................................................


Starting AlphaPept Server
This may take a second..
2021-08-12 18:50:11.569 WARNING streamlit.config:
Warning: the config option 'server.enableCORS=false' is not compatible with 'server.enableXsrfProtection=true'.
As a result, 'server.enableCORS' is being overridden to 'true'.

More information:
In order to protect against CSRF attacks, we send a cookie with each request.
To do so, we must specify allowable origins, which places a restriction on
cross-origin resource sharing.

If cross origin resource sharing is required, please disable server.enableXsrfProtection.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.11.30.22:8501

**Comment by straussmaximilian** [comment]
Okay good!
Did you try to access the page on the Local URL?  (Paste the link into a browser and access?)

**Comment by chaerkadyr** [comment]
Yes, getting introduced to AlphaPept now using iRT files. Thanks so much. I will update with the results later.
