### ISSUE TITLE
mzML support

### ISSUE THREAD

**Issue by brvpuyve** [MannLabs/alphapept#307]
Is there already support for mzML files because Alphapept doesn't seem to recognize the files? 

Best,
Bart

**Comment by straussmaximilian** [comment]
Hi,
the mzml functionality is so far not accessible via the GUI. Do you have a file that you can share? Then I could probably integrate mzml it in the GUI and test.

**Comment by brvpuyve** [comment]
Hi Max,

Awesome, thanks!

I have uploaded an .mzML file (created with MSConvert) of a Human K562 sample acquired on a TripleTOF6600+.
https://filesender.belnet.be/?s=download&token=8e5ddc60-84e2-4fda-8e57-9c4eac2defe2 

Let me know if you would need something else! 

Best,
Bart

**Comment by straussmaximilian** [comment]
Hi Bart,
So I now enabled mzML and tested it with your file and a human HeLa. Below are the results, and I attached the log. Are they in the range that you'd expect? This is the first time we'd run a Sciex file.

I noticed that the mzML did not contain the precursor charge of the instrument, so I had to set it to 0 and use the charge from feature finding; apart from that it did work without additional changes.  The feature finding took quite some time (total time was ~28 minutes with ~20 minutes on FF on an office pc), and it found a lot of features with respect to the number of peptides/proteins - so it could be that some of the default feature finding values are not ideal for this kind of data (e.g. splitting hills if the data is noisy and i.e. one could try the parameter hill_smoothing in the settings)
So let me know if you have any suggestions where we could improve the results / if they are far off.

You can already check the new version (v.0.2.8) [here](https://github.com/MannLabs/alphapept/releases/download/untagged-924e8ba57870f6c1abe9/AlphaPept-Windows-64bit_0.3.28.exe).

There were a couple of more changes coming with this version, and I still wait for the test to run [through](https://github.com/MannLabs/alphapept/actions/runs/1148160789) before releasing it completely and merging to master.

Best,
Max
[2021_08_19_.log](https://github.com/MannLabs/alphapept/files/7017571/2021_08_19_.log)

### 426,599 features | 14,367 peptides | 2,595 protein groups (median)
![newplot](https://user-images.githubusercontent.com/16521288/130139978-4ddb938b-2488-466b-a848-79fdbb6d2e6a.png)

**Comment by brvpuyve** [comment]
Hi Max,

Thanks for looking into this so quickly!! For some reason MSConvert does not add precursor charges when peak picking is performed. Indeed, I could add a treshold peak filter to reduce the level of noise in the data. Good to know that AlphaPept has a similar feature included. 

The number of peptides and proteins seems to be in line with our Mascot search results.  
![image](https://user-images.githubusercontent.com/35368580/130424330-a4150c6c-5cea-4c76-9a60-19b8151d4d19.png)

Thanks again!
Best,

Bart

**Comment by straussmaximilian** [comment]
Awesome! Thanks for testing.
