### ISSUE TITLE
Trypsin the only enzyme? 

### ISSUE THREAD

**Issue by TTCooper-PhD** [MannLabs/alphapept#343]
**Is your feature request related to a problem? Please describe.**
Selection of enzyme. It appears that Alphapept is only suitable for Trypsin-digestion. 

**Describe the solution you'd like**
I would like to be able to create a custom enzyme (similar to MaxQuant). 

**Describe alternatives you've considered**

**Additional context**

**Comment by straussmaximilian** [comment]
Hi,
if you expand the "Modify Settings"-tab and click on FASTA, there is an option to select the Protease.
![Screenshot 2021-09-21 at 11 04 51](https://user-images.githubusercontent.com/16521288/134143528-751e0fb8-aa0f-4374-9324-7eac79f9b3ca.png)

![Uploading Screenshot 2021-09-21 at 11.05.00.png…]()

Is this what you were looking for or would you want to create a completely custom enzyme?

**Comment by TTCooper-PhD** [comment]
Hi, 
Thank you for the quick response. This is what I am looking for and didn't realize the modify settings tab was interactive. I will explore this more before I ask any more questions. 

Best,
Tyler

**Comment by straussmaximilian** [comment]
Awesome! Feel free to post issue or join the discussion page.
