### ISSUE TITLE
Issue with feature finding and proteomics_4d.config file on linux

### ISSUE THREAD

**Issue by PatrickvanZalm** [MannLabs/alphapept#367]
Hi,

Thank you for Alphapept! It looks really good.

Im trying to get it running on a containerized linux environment but run into some issues with feature_finding.py. At line 1761 in feature_finding.py it executes the uff-cmdline2 tool, reading the proteomics_4d.config file. Something seems to go wrong here; it would not read the bool 0 or 1 properly. I did fix that by changing to false/true, respectivly.

Now, it doesnt read the floats properly; 
![image](https://user-images.githubusercontent.com/56233030/141812901-63336f8d-9aca-4461-9bb0-78448877824c.png)

Any idea how I could resolve this? Perhaps a .config file is slightly different between Windows and Linux environments? Or maybe eaiser to get in touch with the Bruker people?

Best,
Patrick

**Comment by straussmaximilian** [comment]
Hi Patrick,
Thanks for your kind words.
As for the Linux version, this is not heavily tested. We have a work-in-progress draft for containerization in docker for Bruker [here](https://github.com/MannLabs/alphapept/blob/master/Dockerfile_bruker).

As I don't have a Linux system at hand, I have just made a quick test on Ubuntu 20.04 LTS on WSL. I used our small [Bruker IRT file for testing](https://datashare.biochem.mpg.de/s/2sWNvImHwdELg55/download). When just calling the feature finder, it runs through but gets a permission error writing the file. I tested changing the access rights for the feature finder with chmod but was not successful. Unfortunately, I am not very proficient in Linux and didn't proceed with troubleshooting the access rights. When I call the feature finder in the terminal directly as sudo with the same arguments, it runs through. Therefore I would assume that the config file is okay.

From the bug, I could imagine that might be a parsing error (e.g., different settings for comma separator in system etc.). 
Attached are some screenshots. I hope his helps
![Screenshot 2021-11-18 at 14 48 45](https://user-images.githubusercontent.com/16521288/142430401-b9f2f68e-d401-4b64-9b21-5a86a293b2a4.png)
![Screenshot 2021-11-18 at 14 56 15](https://user-images.githubusercontent.com/16521288/142430415-2b5b9cd4-ed94-4957-9373-99bd28fd03c2.png)
![Screenshot 2021-11-18 at 14 55 46](https://user-images.githubusercontent.com/16521288/142430422-0ec58d6c-1224-4564-9660-f55f412a24e6.png)
.
