### ISSUE TITLE
Possibility to inactivate fractions missing

### ISSUE THREAD

**Issue by sebastian-vw** [MannLabs/alphapept#389]
**Describe the bug**
In the new AlphaPept version 0.3.31 support of fractions is implemented. When a new experiment is created, all runs are automatically assigned fractions 1 to x. I am not sure what to do when no fractions should be used. I tried to put the fraction from each file to 1, but this doesn't work if many files (>100 are loaded), because there is no function to change the fractions for all files at once and changing file by file takes very long. 

**To Reproduce**
Create a new experiment with version 0.3.31 and observe the file overview. Fractions are automatically assigned to each file. I couldn't find a button to inactivate fractions or change all fractions to the same number (to mimic no fractions).

**Expected behavior**
Time-consuming manual changing of the fraction for each file is necessary and thus this is only possible up to a limited number of raw files to be analyzed.

**Version (please complete the following information):**
 - OS: Win10 Pro
 - Version 0.3.31
 - Installation Type: Python

**Additional context**
It would be great to include a button to inactivate the fractions or at least introduce the option to change the fraction label for all files at once (e.g. to 1).

**Comment by straussmaximilian** [comment]
The idea behind this fraction implementation is that all files that share the same fraction will be scored together. Currently, when loading them they'll be enumerated and each has a unique number, so no file will be in the same fraction, effectively treating them as if there were no fractions.
I could add a note here that explains this behavior.

**Comment by sebastian-vw** [comment]
Thanks for the explanation!
