### ISSUE TITLE
Problem with processing of single timsTOF files

### ISSUE THREAD

**Issue by sebastian-vw** [MannLabs/alphapept#434]
I have experienced a problem when processing single files acquired with a Bruker timsTOF. There is an error in the scoring step and AlphPept gets stuck and doesn't continue.

<img width="958" alt="screenshot_AP" src="https://user-images.githubusercontent.com/60645313/165393681-b2b33a44-5a18-4d2b-8db4-058ae29821dc.png">

This error does not occur when multiple files are processed together.

I have also collected the last entries in the log file:

<img width="934" alt="logs_AP" src="https://user-images.githubusercontent.com/60645313/165393818-92d3fe48-0d65-4ee6-8c41-6f28db095eca.png">

The entries "Calling score_hdf" and "Found second search psms for scoring" and the following ones from this screenshot are not found in the log files when processing more than 1 file.

This behavior was observed with both v0.4.4 and v0.4.5 and with various .d files acquired with a Bruker timsTOF.

**Comment by straussmaximilian** [comment]
This seems to be an issue with related to running on a Threadripper System with more than 60 cores. 
I found an insightful comment here: https://github.com/pycaret/pycaret/issues/38

Will include a process limit.

**Comment by sebastian-vw** [comment]
Hi Max,
thanks for the quick reply, sounds like a good solution.
Thanks!
