### ISSUE TITLE
AlphaPept CLI process hangs on error waiting for user input

### ISSUE THREAD

**Issue by SecretLake** [MannLabs/alphapept#449]
**Is your feature request related to a problem? Please describe.**
When run as a CLI process - if an error is encountered and the run fails - AlphaPept hangs waiting for user input.
This is probably done to let the user see the error. However, it makes automated monitoring of the CLI process more difficult. E.g. any automated pipeline that runs multiple AP instances via the CLI has to parse the standard output of the process in order to see if an error has been encountered (there is no error info in the log file and the process keeps hanging).

**Describe the solution you'd like**
A better solution would be to:
- Write the error to the log file and STDERR
- Fail the CLI process after the error has been encountered and handled

**Describe alternatives you've considered**
- At the moment we rely on parsing STDOUT of the CLI process and then killing it from an automated pipeline. This seems like a rather fragile solution.

**Additional context**

Screenshot of the issue: <img width="781" alt="Screenshot 2022-05-18 at 14 59 54" src="https://user-images.githubusercontent.com/44067777/169045259-c72a5599-ca20-455d-9699-ce27f4ff0f5d.png">

Location of the input request in the code: https://github.com/MannLabs/alphapept/blob/46bfa52998fb2bbb599e6cbb100ea1524865b7c1/alphapept/__main__.py#L24

**Comment by straussmaximilian** [comment]
Yes, sounds great. Could you create a PR for this?
