### ISSUE TITLE
Breaking changes in output files, e.g., column names

### ISSUE THREAD

**Issue by felixriese** [MannLabs/alphapept#459]
As written in the [changelog for some 0.4.x versions](https://github.com/MannLabs/alphapept/releases/tag/0.4.4), some changes in namings are included:

> This version contains a lot of variable renaming to be more consistent with other Alpha*-packages. This will probably lead to incompatibility with previous history modes.

For **backward compatibility**, I am sharing some changes which might help also others:

* Sample names are not ending on `.ms_data.hdf` anymore. This suffix seems removed.
* In the peptide table, these columns seem to be changed:
    * `'mobility_calib' -> "mobility"` (or removed?)
    * `'int_sum' -> "ms1_int_sum"`
    * `'naked_sequence' -> 'sequence_naked'`
    * `'int_sum_dn' -> 'ms1_int_sum_dn'`
    * removed trailing space in `"prec_offset_raw ", "prec_offset_raw_ppm "`

---

**To the `alphapept` developers:** could we include these (for me as a user) breaking changes in the future in the changelog? This can be supported by the community, of course 💪😊

**Comment by felixriese** [comment]
Just for the documentation: column names of the peptide table seem to have changed in AlphaPept [`0.4.6`](https://github.com/MannLabs/alphapept/releases/tag/v0.4.6):
* Removed `"ms1_int_sum_dn"`
* Changed `"ms1_int_sum"` to `"ms1_int_sum_apex"`

**Comment by straussmaximilian** [comment]
Note that "_dn" will always be added when there is delayed normalization.

Closing this, for now; feel free to comment in case there is more in the future.
