### ISSUE TITLE
 Still problems with processing of single timsTOF files 

### ISSUE THREAD

**Issue by mschwoer** [MannLabs/alphapept#488]
**Describe the bug**
The error described in #434 still occurs on machines with > 60 cores, regardless of the `n_processes` settings.

**Comment by mschwoer** [comment]
The root cause is that the `n_processes` settings are not propagated to `score.py:train_RF()`. Thus, the default value `n_jobs: int = -1` is always used there, which makes `GridSearchCV` (according to doc) always use the maximum number of cores available. If this is bigger than 60, the crash described in #434 occurs.

Suggested solution:
- pass `n_processes` settings to `score.py:train_RF()`.
- (optional) to make `train_RF()` itself robust against this issue, introduce another cpu core check (similar to the solution in 7e989bc)

**Comment by straussmaximilian** [comment]
Was closed with #489. Feel free to reopen in case anything else comes up.
