### ISSUE TITLE
nbdev upgrade breaks CI

### ISSUE THREAD

**Issue by mschwoer** [MannLabs/alphapept#490]
**Describe the bug**
`nbdev` had a major rewrite (https://github.com/fastai/nbdev/releases/tag/2.0.0) including breaking changes, such that the CI pipeline does not work anymore. As the `requirements.txt` has `nbdev>=1.1.22`, this latest version is pulled.

**To Reproduce**
see https://github.com/MannLabs/alphapept/runs/7787447345?check_suite_focus=true

**Additional comments**
don't forget to update the docu :-)
https://github.com/MannLabs/alphapept/blob/master/docs/contributing.html

**Comment by straussmaximilian** [comment]
NBDEV is now updated on develop and will be merged soon.
