### ISSUE TITLE
AlphaPept GUI 0.5.1  Breaking change: The data editor's representation in st.session_state was changed.  

### ISSUE THREAD

**Issue by grandrea** [MannLabs/alphapept#553]
**Describe the bug**
Loading new experiment folder triggers the warning

    Please replace st.experimental_data_editor with st.data_editor.

    st.experimental_data_editor will be removed after 2023-09-01.

    Breaking change: The data editor's representation in st.session_state was changed. The edited_cells dictionary is now called edited_rows and uses a different format ({0: {"column name": "edited value"}} instead of {"0:1": "edited value"}). You may need to adjust the code if your app uses st.experimental_data_editor in combination with st.session_state."

**Version (please complete the following information):**
 - Linux
 - 0.5.1 stable gui
 
 installed as follows
 
    conda install -c conda-forge mono
    pip install "alphapept[gui,stable]"
    pip install pythonnet>=2.5.2

When I submit a run, I get a crash in mono/thermo .raw conversion, which previously (version 0.4.1 i think) used to work.
[alphapept_log.txt](https://github.com/MannLabs/alphapept/files/12792225/alphapept_log.txt)

**Comment by straussmaximilian** [comment]
Thanks for reporting. This should be fixed now.

**Comment by straussmaximilian** [comment]
Hi, this would have been the github version.
Now I pushed it to GitHub,
so it should be installable via pip. You could try `pip install alphapept --upgrade`, if this doesn't work I would try a clean install with "alphapept[stable,gui-stable]"
