### ISSUE TITLE
A question about guide

### ISSUE THREAD

**Issue by lnelllwj** [MannLabs/alphapept#555]
There is an sample below "convert_connections_to_array" on the "https://mannlabs.github.io/alphapept/feature_finding.html".
The result of connections that is "centroids = np.array([10, 20, 30, 10.2, 20, 10, 30, 40])" is "from_idx=[0, 1, 2], to_idx=[3, 4, 6]" in your page.
I think the right result is "from_idx=[0, 1, 2, 3], to_idx=[3, 4, 6, 5]".
Is my inderstanding wrong?

![guide](https://github.com/MannLabs/alphapept/assets/33108987/31939e8b-66f8-475c-808e-9999f05e6021)
![guide](https://github.com/MannLabs/alphapept/assets/33108987/fdff702b-e9f9-4964-bcb7-75d413d03370)

**Comment by lnelllwj** [comment]
The second photo is this. I pushed same photos.
![correct](https://github.com/MannLabs/alphapept/assets/33108987/f6457fc2-ead8-4290-887a-8af9d49efa3f)

**Comment by straussmaximilian** [comment]
Hi, yes the code snippet was faulty. I revised it now and will push.

```
#Sample snippet to show centroid conncetions

import matplotlib.pyplot as plt

row_borders = np.array([3, 5, 7])
rowwise_peaks = np.array([3, 2, 3])
max_gap = 2

score = np.full((3,3, max_gap), np.inf)
connections = np.full((3,3, max_gap), -1)

centroids = np.array([10, 20, 30,
                      10.2, 20,
                      10, 30, 40])

centroid_tol = 0.5*1e5

from_idx, to_idx, score_median, score_std = connect_centroids(rowwise_peaks, row_borders, centroids, max_gap, centroid_tol)

scan_no = np.array([0, 0, 0,
                    1, 1,
                    2, 2, 2])

print(f'Centroid Connections from {from_idx} to {to_idx}')

plt.figure(figsize=(5,5))

colors = ['r','g','b']

for x,y in zip(centroids, scan_no):
    plt.plot(x, y, '.', color=colors[y])

for i, _ in enumerate(from_idx):
    from_ = _
    to_ = to_idx[i]
    plt.plot([centroids[from_], centroids[to_]], [scan_no[from_], scan_no[to_]], 'k:')
    
plt.ylabel('scan')
plt.xlabel('m/z')
plt.ylim(len(row_borders)+1.5, -1.5)
plt.title('Peak connections')
plt.show()
```
and should give this plot:

![image](https://github.com/MannLabs/alphapept/assets/16521288/b657c60f-44b6-482a-9d98-7ce881e37b2a)
