### ISSUE TITLE
KeyError: 'Modified.Sequence'

### ISSUE THREAD

**Issue by yanzhou-boy** [MannLabs/alphapept#563]
Dear creator, when I was building the prediction model, the DIA-NN database search data imported and the raw file dismounted showed errors as shown in the following figure. The 'Modified.Sequence' field data cannot be found in the DIA-NN data, what is the reason for this? I checked the file and found that it contained the 'Modified.Sequence' 
![1724322778794](https://github.com/user-attachments/assets/23412544-af5a-4c63-9517-9850b0bc05ca)
column, but peptdeep still reported the error

**Comment by straussmaximilian** [comment]
It looks like this is meant for alphapeptdeep?
Could you post the issue here?

https://github.com/MannLabs/alphapeptdeep
